### ISSUE TITLE
waiting to transcribe... never transcribes

### ISSUE THREAD

**Issue by thephm** [maxkrieger/voiceliner#11]
Device: Samsung S20 5G
Location: Ontario, Canada (in case that matters) 

Steps
1. Installed app
2. Made 3 brief recordings

Expected result: see transcription quickly
Actual result: still waiting, 10 mins and no error
![Screenshot_20211212-101110](https://user-images.githubusercontent.com/8527588/145718155-0b5b5a77-8623-4003-b47c-414f57cf5458.jpg)

**Comment by maxkrieger** [comment]
Thanks for opening an issue! Can you try relaunching and adding another note? Also I assume you had an internet connection when you were trying this?

**Comment by thnewlands** [comment]
Same problem! I tried your solution but didn't have any luck. I've only run the app so far on the WiFi I'm posting this on. 

S20 Ultra here.

**Comment by thephm** [comment]
Yes tried a few things, I was on Wi-Fi. Tried restarting app. Tried on cellular data. No workaround so far

**Comment by azf20** [comment]
I see the same, tried relaunching and adding a new note, no luck. On Android.

**Comment by ryanramage** [comment]
Same issue here. Android, Samsung note 10 plus.

**Comment by joshuahhh** [comment]
Me too! Pixel 4a. Happy to help debug.

**Comment by cannibalox** [comment]
same issue, Huawei Mate 20 pro android 10.

**Comment by maxkrieger** [comment]
So sorry all - it worked in the simulator 😓  especially annoying since yall have to generate your own azure keys to help..

**Comment by elliotsayes** [comment]
Debug log on a S8, not sure if this is useful since I don't have an AZURE_SPEECH_KEY"
https://gist.github.com/elliotsayes/e08eb51edb0001f318677847cb139261

**Comment by maxkrieger** [comment]
Rolling out an update that may or may not fix this, lemme know what you see when the update hits! If it's what I think (bad API key) then I should get tons of error logs.

**Comment by azf20** [comment]
It's working! Thanks so much @maxkrieger

**Comment by maxkrieger** [comment]
WTF. I hate this hahahaa. Was relying hard on a Stackoverflow comment for proper `--dart-define` usage. React 👍 to this if it's working for y'all!

**Comment by maxkrieger** [comment]
Alright I'm gonna close this, thanks everyone for bringing this to my attention!
