### ISSUE TITLE
write note with keyboard 

### ISSUE THREAD

**Issue by MaxBittker** [maxkrieger/voiceliner#15]
don’t always want to talk!

i see this is currently possible via recording a 0 second note and editing it

**Comment by maxkrieger** [comment]
Totally, the "barrier" was figuring out where the button goes lol. Maybe a placeholder "constructor" note on the bottom. Or long-tap on the blank space. Or if it's a toggle in the settings ppl can cope with left-floating the record button and smooshing in a smol text button as well. Did you have another idea in mind?

**Comment by MaxBittker** [comment]
Philosophically, how would you feel about solutions that privilege text
input equally to voice?

For instance, two buttons side by side for everyone, or using the camera
interface button behavior ( tap=photo, hold=video) except tap= text entry,
hold =speaking

**Comment by robinsloan** [comment]
I am thinking/wondering about the same interactions, and just wanted to mention that it might be wise to "save" the tap for hands-free recording. Which hardly seems necessary in Flâneur Mode, I know, but I just spent a season driving a ton & yapping notes into my phone all day.

**Comment by maxkrieger** [comment]
> Philosophically, how would you feel about solutions that privilege text
> input equally to voice?

Not opposed!

> For instance, two buttons side by side for everyone

This might be an ergonomics thing - I'm a leftie phone holder and would want the voice button to be on the left so I can thumb it. Maybe can just have a setting to swap it? 😅

**Comment by maxkrieger** [comment]
@MaxBittker gave a great idea to try which is nestling a lil' text button in the existing record button pill, like how iOS does it:
![image](https://user-images.githubusercontent.com/2660634/147377107-9730d02f-00cc-402b-9cb4-4aec707d7bfd.jpeg)

I'm rolling out "tap and hold in the negative space to open a context menu with text note button" as a stopgap. I should also add it to the ellipsis menu.

**Comment by maxkrieger** [comment]
Closing this for now but open for UX improvements
