### ISSUE TITLE
Select languages in-app: Multilingual transcription setting 

### ISSUE THREAD

**Issue by maxkrieger** [maxkrieger/voiceliner#17]
Need to enumerate locales, probably based on BCP-47

https://docs.microsoft.com/en-us/azure/cognitive-services/speech-service/language-support#speech-to-text

https://developer.apple.com/documentation/speech/sfspeechrecognizer/1649877-init

**Comment by maxkrieger** [comment]
This is resolved for Android, iOS coming soon.

**Comment by wenlzhang** [comment]
Is it also possible to support transcribing mixed languages? E.g. other languages mixed with English words?

**Comment by maxkrieger** [comment]
Rolling out iOS now!
