### ISSUE TITLE
Not useful response to tapping record button

### ISSUE THREAD

**Issue by elliotsayes** [maxkrieger/voiceliner#18]
If you tap the record button, it makes a very short, pretty much empty recording.
It would make more sense if the UI did something else, like:
- ignored taps
- toggled on record mode until tapped again

though not sure if the latter fits the intended workflow of recording quick, individual thoughts.
but maybe this could go well with a future feature that lets you slice up larger recordings.

**Comment by maxkrieger** [comment]
Yeah I didn't put much thought into the tap detection - code is in `record_button.dart`. I guess we could run a timer and go into "continuous mode" if the finger goes up within 1s.

**Comment by tfiers** [comment]
Yes exactly, that's what I thought the behaviour would be intuitively.
A "locked" mode like that would be great.
(Though the physicality of keeping a finger pressed is interesting).

This brings us to longer recordings. I tend to make long ones, just made a 403 sec one here. A scrubber for playback of them would be nice.

Might learn Flutter some time and contribute.

Btw thanks for building and bringing this out, it's very resonant.

**Comment by maxkrieger** [comment]
Rolling this out!

**Comment by harrybiddle** [comment]
Hey! I came here to request a "lock" recording mode. I've been using this app on walks (it's wonderful, thank you) and having to keep my thumb on the screen the whole time is a bit of a pain. It sounds like this will be released soon? 

Thank you for your efforts on this project 😊

**Comment by maxkrieger** [comment]
@harrybiddle just tap the record button!

**Comment by harrybiddle** [comment]
Oh my, that works! I had no idea 😁. Thanks.
