### ISSUE TITLE
hiding completed notes causes future notes to indent under the now hidden note

### ISSUE THREAD

**Issue by roytemple** [maxkrieger/voiceliner#19]
If you have it set to hide completed notes, when you record subsequent notes, future recordings are indented under the now hidden notes instead of being added to the bottom - which is the behavior if you have no completed notes.

**Comment by maxkrieger** [comment]
Thanks, this is a great bug. Will take a look later

**Comment by maxkrieger** [comment]
Fixed in next update

**Comment by roytemple** [comment]
So dumb question which I should probably know but I'm new to Github. You did a new release yesterday. Is the only way to use that to wait for it to update from the app store? (iOS)
