### ISSUE TITLE
Feature Request: Add ability to record voice hands-free (voice memo)

### ISSUE THREAD

**Issue by aayushdutt** [maxkrieger/voiceliner#31]
Thanks for this awesome app! 
I'd love to use this as a voice diary, where you are just taking a walk and talking through your thoughts in your earphones. It could transcribe and organise your voice memos.

**Comment by maxkrieger** [comment]
This isn't very well-specified but sounds like a duplicate of #18. Anything more ambitious than that and you're welcome to fork/PR!
