### ISSUE TITLE
App-specific options when selecting text on Android

### ISSUE THREAD

**Issue by Narretz** [maxkrieger/voiceliner#34]
Cool app, really like the flow so far.

Sorry if the description is a bit unclear, I don't know the exact Android terms.

Some apps expose a special interface when you select text. For example, AnkiDroid lets you create a new card in the "3 dots" menu of the selection popover. 

Now in Voiceliner, I can select the transcribed text via the Edit modal.

But when I select text, I only see the three options "Cut" "Copy" and "Paste".

Could support for app-specific interfaces be added? Or is it maybe not possible with Flutter?

**Comment by maxkrieger** [comment]
What types of options would you want? This might be possible

**Comment by Narretz** [comment]
The option I would like is for https://tasks.org/

But as far as I understand it, you wouldn't add support for a specific app to Voiceliner, but for this extension in the selection menu in general. I might be wrong though.

**Comment by maxkrieger** [comment]
This is a bit out of scope I think, you're welcome to send a PR in!

**Comment by Narretz** [comment]
I *think* this is currently impossible, as Flutter implements a custom selection menu that only allows these three options: https://api.flutter.dev/flutter/widgets/ToolbarOptions-class.html (via TextField -> EditableText)

That also explains why the options are in English and not in German for me, like in other apps.

Disappointing by Flutter, but nothing that can be changed atm.
