### ISSUE TITLE
Investigate alternative transcription solutions for Android

### ISSUE THREAD

**Issue by maxkrieger** [maxkrieger/voiceliner#37]
An HN commenter suggested https://github.com/alphacep/vosk-api. We'd have to write a binding and make sure the 50mb bundle stays in the Android folder, not the iOS build. The API is a little unclear https://github.com/alphacep/vosk-api/tree/master/java 

https://github.com/alphacep/vosk-android-demo/blob/b0035656cb39b77318a8c0b75f9ca9ea61b20884/app/src/main/java/org/vosk/demo/VoskActivity.java#L233

**Comment by maxkrieger** [comment]
Unfortunate tradeoff is each language adds another 50mb. Will probably just bundle english and maybe someone can contribute a way to auto download others, or I can charge for non English users to use azure.

**Comment by lyz-code** [comment]
Maybe a middle point is for the program to autodiscover the language models in a directory. That way we wouldn't need to code a feature to download others, we'll just need to add in the documentation some guidelines on how to download them and where they need to put it

**Comment by maxkrieger** [comment]
https://github.com/KangRuiYu/voice_scribe/ looks like a lovely implementation of Vosk in Android/Flutter

Here's some model downloading code, not sured if Vosk devs care about their servers being pinged by every user.. https://github.com/KangRuiYu/voice_scribe/blob/main/lib/models/model_downloader.dart 

I think I'll bundle the English model

**Comment by thelazyoxymoron** [comment]
Would love to see this getting implemented! Unfortunately, not a mobile developer myself but can help out with testing.

**Comment by maxkrieger** [comment]
This is deploying momentarily!
