### ISSUE TITLE
Enhancement: Language of Transcribe Feature based on user setting 

### ISSUE THREAD

**Issue by marcopaga** [maxkrieger/voiceliner#40]
The iOS transcription uses an english default to create transcriptions.
https://github.com/maxkrieger/voiceliner/blob/66f01fc8813562353f2596ac9bc38b885863f636/lib/repositories/ios_speech_recognizer.dart#L10

I suggest taking the user locale or a setting to configure the language.

**Comment by maxkrieger** [comment]
Duplicate of #17
