### ISSUE TITLE
feature request: allow grouping notes by day (e.g. like in roam)

### ISSUE THREAD

**Issue by kiprasmel** [maxkrieger/voiceliner#43]
i used to use notion and there you'd have to create categories / group stuff into folders, like in the file system.

what roam opened my eyes on is that you don't need to do that & it's a waste of time & wrong mindset. it's not a top-down tree, like a directory, it's a graph with connections in all sorts of weird and unexpected ways (& that's good!).

currently in voiceliner i just have one group "default" or whatever and i take all my notes there.\
if i could go into a mode or something, that would group the notes taken in that group by the day, and on each day when i open the app a new daily group would be auto created (or just when you take a note it ends up in a new daily notes layer), it'd be great!

hope the "group" stuff isn't confusing - i just want a simple separation between notes taken in different days (like a border between the days), while still being able to scroll thru the different days like infinite scroll. i.e. just like in roam

**Comment by maxkrieger** [comment]
I thiiiink this is related to #14? The auto creation is probably out of scope, I assume you noticed that the default name for new outlines is the date

**Comment by maxkrieger** [comment]
This is pretty much done with the new timeline view, I'll add refinements like day and temperature sorting later on
