### ISSUE TITLE
Exporting outline markdown from iOS - "copy" not working as expected

### ISSUE THREAD

**Issue by bschlagel** [maxkrieger/voiceliner#52]
When I go to share an entire outline from iOS ("export markdown") the most prominent action, just below the shortcut rows of messaging / app destinations, is "Copy".

What I expect: when I hit "Copy" it will copy the full markdown of my outline, and I can then paste as text in any other app.

What happens instead: it seems that the file (filename?) is copied; when I paste it only pastes the title of the outline. So I'm unable to e.g. copy and paste directly into Obsidian, instead I'm using the workaround of emailing myself the markdown file then opening and copy-pasting from there, which works but is a couple extra steps!

One suggestion that'd be a bigger change but also help make #12 and #28 possible would be to add an in-app export settings modal before the default mobile OS share panel, where you could toggle settings e.g. to include timestamps or checkboxes, and then maybe like "share as file" or "share as text".

**Comment by maxkrieger** [comment]
Rolling out!
