### ISSUE TITLE
Where to find the backup in Google Drive?

### ISSUE THREAD

**Issue by devonzuegel** [maxkrieger/voiceliner#62]
I've been trying to find the backup file in Drive so that I can do some other fun stuff with the data, but haven't been able to figure out what the file is called. According to the code (below) I expected it to be something like `voice_outliner-TIMESTAMP.zip` but didn't see a file with that name anywhere in my Drive.

https://github.com/maxkrieger/voiceliner/blob/bbc7832af7a1dcc048796eb79d250f6bcd5ac894/lib/repositories/drive_backup.dart#L104-L113

From playing around with it, my backup does seem to be working, so it seems to be creating a file somewhere. I just can't figure out what the file is called!

P.S. Thank you for making VoiceLiner! I've been wanting exactly this tool for ages.

**Comment by maxkrieger** [comment]
Hi Devon, glad you like the app! Was super uncanny to see that thread of yours about similar needs when I launched it.

Unfortunately, afaik, the gdrive “app specific data” scope doesn’t allow the files to be visible for end users (https://developers.google.com/drive/api/v2/api-specific-auth?hl=en#identify_whether_to_use_a_restricted_scope). I can only upload to the user’s visible file system if I get full access to their drive, which isn’t ideal.

Fortunately, all your data is easily accessible in the iOS file system, including/especially the sqlite database. You can zip everything straight from the Files app, and I think iCloud is backing up a bit. There might be a way to do this with shortcuts too?

 I might add Dropbox support eventually as a stopgap for #8

**Comment by devonzuegel** [comment]
Ahhh that makes sense. Having the sqlite db in iCloud might actually be better for my purposes, so I'm actually glad to hear that!

---

> I might add Dropbox support eventually as a stopgap for #8. They do provide app restricted user navigable scope.

This would be amazing!

---

Two ideas that you can of course take or leave:
- It might be helpful to have documentation about that in the app somewhere, so that other people can figure out where the data is stored.
- I'd also love to have it in plaintext rather than a zip/sqlite db, because then I can auto-sync it to my Logseq directory.

**Comment by benjaffe** [comment]
I also want to sync it to Logseq. A different solution would be auto-export to markdown, since I'd prefer to not have to export manually each time.

This is an amazing app, and so glad I discovered it. <3

**Comment by maxkrieger** [comment]
I made an issue #65 but I probably won't get to it anytime soon - lmk if you wanna add the feature & I can give codebase pointers
