### ISSUE TITLE
[Feature request] Allow retranscription

### ISSUE THREAD

**Issue by mileyvirus** [maxkrieger/voiceliner#75]
Hello there, Max. Great work with the language selection on iOS.

I was wondering if you'd consider adding a new item in each recording's context menu (the ⋮ menu) name something like "Transcribe again". I now have a lot of notes in another language but transcribed in English. It would also be helpful for folks that record in multiple languages if it was more granular like "Transcribe with language…" and then we present a language selection modal.

Anyway, thanks for your amazing app. I wish you the best ❤️

**Comment by maxkrieger** [comment]
Rolling out retranscribe feature!
