### ISSUE TITLE
App not compatible with device in play store

### ISSUE THREAD

**Issue by karmanyaahm** [maxkrieger/voiceliner#77]
Hi,
I installed voiceliner after seeing it on HN a while ago and I loved it. However when I tried updating it from the play store recently, it said your device is not compatible, contact developers for more info. Is there some criteria devices need to fulfill to be compatible? It was working perfectly before.

I have a Xiaomi Mi A2 with Android 10.

**Comment by maxkrieger** [comment]
Don't you have to sideload google play for Xiaomi devices? Unfortunately that means it's extra work on my end which I'd rather not do. One option is building the apk yourself and sideloading it!

**Comment by karmanyaahm** [comment]
No, my phone came with play by default. I think you might be thinking of Huawei which doesn't have play by default.

**Comment by ichmoimeyo** [comment]
Hi, I have a related issue:

Android phone I have version 1.22.3 -  **split_config.arm64_v8a.apk**
Chromebook I have version    1.21.6 -  **split_config.x86_64.apk** and am unable to update it as "it is no longer compatible ... Contact the developer"

When you have time would you make an updated **x86_64** version available again please?

[I have an Acer Chromebook Spin 512 12"]

**Comment by asheingold** [comment]
I'd love to use this on my Chromebook as well. In addition, I (might) be able to fix #72, if I read the code right.

@maxkrieger - I'd be willing to take this issue (I think), but I don't have much experience with Android development.  Once I check a few things and get my development environment set up, I'll try and fix the issues and submit PRs.

**Comment by maxkrieger** [comment]
@asheingold lovely thanks!

**Comment by backmind** [comment]
> Hi, I installed voiceliner after seeing it on HN a while ago and I loved it. However when I tried updating it from the play store recently, it said your device is not compatible, contact developers for more info. Is there some criteria devices need to fulfill to be compatible? It was working perfectly before.
> 
> I have a Xiaomi Mi A2 with Android 10.

Same here. Can't download by "not compatible device" on play store.

Xiaomi Mi 8, MIUI 12.0.3

**Comment by maxkrieger** [comment]
Rolling out an update to Play Store with a way lower `minSdkVersion` (API 21). This should expand the range of devices that can use Voiceliner! Do try in the next few hours...

**Comment by karmanyaahm** [comment]
I can update it, thanks! (Feel free to close if everyone's issue has been solved)
