### ISSUE TITLE
Google Drive Sign in doesn't work on android

### ISSUE THREAD

**Issue by maxkrieger** [maxkrieger/voiceliner#8]
Related to SHA-1 fingerprint - [API Exception 10](https://stackoverflow.com/questions/49450140/google-signin-api-exception-10)

Can anyone familiar with the API help out? https://github.com/maxkrieger/voiceliner/blob/main/lib/repositories/drive_backup.dart

**Comment by maxkrieger** [comment]
I think I fixed it, switched my OAuth provider's fingerprint to the SHA-1 under `App Integrity` in the google play console.

**Comment by dabreegster** [comment]
I'm also hitting this on the current Play Store version. I get to the "choose an account" screen, click my email, and get a "Couldn't sign in" message at the bottom. Something else flashes by, but no idea what. Let me know what else I can do to help debug.

Thanks for the app, by the way! I've been on the hunt for something really simple to record notes to later tag in OpenStreetMap, and so far this is the closest fit.

**Comment by dmje** [comment]
Same bug for me on Android. 

Amazing app btw 👍

**Comment by parth-patil** [comment]
I am seeing the same issue, due to which I can't backup my notes to Google drive. Please look into this issue

**Comment by maxkrieger** [comment]
I have very little clue how to fix this. Android folks‘ll need to help out a bit.

**Comment by RichardFoxworthy** [comment]
Same problem for me. I'm hoping gdrive backup would write markdown files to a directory? This should allow easy access to transcribed voiceliner notes from Logseq / Obsidian, right?

**Comment by maxkrieger** [comment]
I think I fixed it, update rolling out soon.
