### ISSUE TITLE
Language selection not remembered

### ISSUE THREAD

**Issue by jamesscottbrown** [maxkrieger/voiceliner#80]
When I open voiceliner (on iOS 15.5), I am often shown the "Setup" page asking me to "Select transcription language"; this setting seems to not be being saved.

This seems to happen if I haven't opened Voiceliner for a while, but I can reliably reproduce this by [closing the app](https://support.apple.com/en-gb/HT201330) then re-opening it.

**Comment by jamesscottbrown** [comment]
It looks the value should be being saved [here](https://github.com/maxkrieger/voiceliner/blob/c2813ba481631268bd8c33587a7bb307ae8146b3/lib/widgets/ios_locale_selector.dart#L47); I'm not familiar enough with Dart to debug.

**Comment by maxkrieger** [comment]
Dumb bug on my part - I don't save to storage if you don't select an item from the list. Rolling out in next update
