### ISSUE TITLE
Off-line voice transcription

### ISSUE THREAD

**Issue by lyondhur** [maxkrieger/voiceliner#81]
At the moment voice transcription cannot be done without data access. 

It would be great if transcription could be done within the device - offline - without the need of a data connection — both for speed, practical and also security purposes.

**Comment by DarthPleurotus** [comment]
Hmm I am having no trouble getting voice transcription to work. Are you on an Apple device?

**Comment by lyondhur** [comment]
Read it again please. 

It's not an issue, but a feature idea/request.

**Comment by lyondhur** [comment]
Read it again please. 

It's not an issue, but a feature idea/request mate. 

Works perfectly 'online'.

**Comment by DarthPleurotus** [comment]
Ah I left out a word there-- I am having no trouble getting **offline** voice transcription to work (in airplane mode on an Android device).

**Comment by maxkrieger** [comment]
Closing this as you opened a duplicate #82
