### ISSUE TITLE
Unable to download any transcription packages.

### ISSUE THREAD

**Issue by pedro-ratti** [maxkrieger/voiceliner#89]
I am unable to download any transcription packages.
It shows the following error:
![c5258364-55e5-487a-b74e-41d51bebc01e](https://user-images.githubusercontent.com/109469753/193420288-5fea1d6b-f4fe-4385-94a4-7a2c63d84e08.jpg)

**Comment by maxkrieger** [comment]
I could not reproduce this - the Spanish package works fine for me. If you navigate to the URL in the error, does the .zip download properly?

**Comment by pedro-ratti** [comment]
Hi Max.

 I can manually download the package from that location, but I don't know what folder I should put it in for it to work with the app.


 Thanks.

Pedro Ratti.

Obtener Outlook para Android<https://aka.ms/AAb9ysg>

________________________________
De: Max Krieger ***@***.***>
Enviado: lunes, 3 de octubre de 2022 00:19
Para: maxkrieger/voiceliner ***@***.***>
Cc: Pedro Antonio Ratti ***@***.***>; Author ***@***.***>
Asunto: Re: [maxkrieger/voiceliner] Unable to download any transcription packages. (Issue #89)


I could not reproduce this - the Spanish package works fine for me. If you navigate to the URL in the error, does the .zip download properly?
