### ISSUE TITLE
When editing long notes on iOS, text box overflows / does not scroll

### ISSUE THREAD

**Issue by bschlagel** [maxkrieger/voiceliner#91]
I'm finding for long notes (beyond around a minute), when the text transcription becomes longer than [one phone screen height minus keyboard], the text overflows the edit modal rather than scrolling. Since I can't scroll it becomes impossible to edit the latter part of the note.

**Comment by maxkrieger** [comment]
oof will take a look!

**Comment by maxkrieger** [comment]
Rolling out in update!
