### ISSUE TITLE
Back up to iCloud

### ISSUE THREAD

**Issue by jakemkc** [maxkrieger/voiceliner#93]
Hi all,

From https://a9.io/voiceliner/, it stated You can back up to "Google Drive and iCloud"

I have an iphone 7 with iOS 15.7.1 (latest) and latest Voiceliner installed from app store.

I tried to figure out where I can backup to iCloud in the app setting but only see option to backup to Google Drive (see screenshot below)

Browsing with File app I can see "Voiceliner" folder in "on my iPhone" but not "iCloud Drive" location.

I wonder am I missing something? 

Thanks.

Jake

![IMG_162115961455-1](https://user-images.githubusercontent.com/18485734/205743620-cc415288-3d0e-4fce-839d-50ad4a0cd383.jpeg)

**Comment by maxkrieger** [comment]
Ah yeah I should put a note. Go to the Settings app > Voiceliner > Document Storage > iCloud Drive.

The data is also accessible through the Files app!

**Comment by maxkrieger** [comment]
btw your research is super cool, you're asking the questions we all want to know!! curious if there are digital tooling gaps in exposomics, pollutants are an important issue to me and I'd like to make more open source contributions to biology software.

**Comment by jakemkc** [comment]
Thanks!

For your question: exposomics studies typically look at one or more classes of chemicals. Circular visualization of the relationships can be done with Circos or similar packages in R. However, these options take quite an amount of time to learn before getting a plot.

If you know web development, I think making the visualization accessible could be a great move. 

Jake

**Comment by maxkrieger** [comment]
That sounds like a great project, I'll get in touch if I get around to it. Thanks!
