### ISSUE TITLE
App Not Saving To iCloud Drive When Option Enabled

### ISSUE THREAD

**Issue by tracerte** [maxkrieger/voiceliner#99]
Hi,
I have an iPhone XS Max running iOS 16.3.1 and the latest version of Voiceliner. I installed the app today and have been playing with it. I noticed that my app data is not being backed up to iCloud Drive despite setting the Document and Storage option to iCloud Drive. The app data is being saved only to the iPhone local storage as per the location of the Voiceliner folder in the Files App. I have followed the instructions in issue #93 without luck.

The app has worked beautifully otherwise.

Thanks for this useful and thanks in advance for any assistance.

**Comment by maxkrieger** [comment]
Hey, the app uses icloud *backup*, not icloud drive. You can confirm it's being backed up by going to

* Settings
* Apple ID
* iCloud
* iCloud Backup
* All Device Backups / [Your device's name]
* Confirm Voiceliner's in the list

I'm closing this for now and you can make a separate issue as a feature request if you want iCloud drive support specifically, which is a significant project.
